config/routes.rb
ContentPlanner::Application.routes.draw do
  resources :contents

  root to: "home#index"

  resources :content_plans do
    member do
      get 'versions'
      get :xls_export
    end
  end

  resources :tasks

  resources :comments do
    member do
      post :reply
    end
  end

  resources :users

  resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]

  get "dashboard_data", to: "home#dashboard_data"
  get "chart", to: "home#chart"

  get "/healthcheck" => proc { [200, {}, ["OK"]] }

end

app/models/content_plan.rb
class ContentPlan < ActiveRecord::Base
  include Versioning
  include Organisations

  acts_as_taggable

  paginates_per 15

  QUARTERS = 1..4
  YEARS = Time.now.year..(Time.now + 2.years).year

  has_many :tasks,    -> { order(done_at: :asc, id: :desc) }, dependent: :destroy, as: :taskable
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy, as: :commentable

  has_many :content_plan_needs, dependent: :destroy
  has_many :needs, through: :content_plan_needs

  has_many :content_plan_users
  has_many :users, through: :content_plan_users

  has_many :content_plan_contents, dependent: :destroy
  has_many :contents, through: :content_plan_contents

  scope :due_date, ->(quarter, year) {
    scope = all
    scope = scope.where(due_quarter: quarter) if quarter.present?
    scope = scope.where(due_year: year) if year.present?
    scope
  }

  scope :contents, -> {
    Content.where(id: all.map(&:content_plan_contents).flatten.map(&:content_id).uniq).
      order("contents.ref_no")
  }

  validates :title, :ref_no, presence: true, length: { maximum: 255 }

  # Caching
  before_save do
    contents.each { |record| record.touch }
  end

  def name
    "#{ref_no} - #{title}"
  end
  alias_method :to_s, :name

  def size
    contents.map(&:size).compact.sum
  end
end

app/models/need.rb
class Need < ActiveRecord::Base
  has_many :organisation_needs, dependent: :destroy
  has_many :organisations, through: :organisation_needs

  has_many :content_plan_needs, dependent: :destroy
  has_many :content_plans, through: :content_plan_needs

  has_many :content_needs, dependent: :destroy
  has_many :contents, through: :content_needs

  validates :api_id, presence: true, uniqueness: true

  def org_names
    organisations.map(&:abbreviation)
  end

  def to_s
    "[#{api_id}](#{org_names.join(', ')}) #{story}"
  end

  def story
    "As a #{role} I want to #{goal} so that #{benefit}"
  end
end

app/controllers/content_plans_controller.rb
class ContentPlansController < ApplicationController
  helper_method :sort_column, :sort_direction, :content_plan_filter

  expose_decorated(:content_plan, attributes: :content_plan_params)
  expose_decorated(:content_plans) {
    ContentPlanSearch.new(params[:search]).results.page(params[:page])
  }
  expose(:comment) {
    current_user.comments.build(commentable: content_plan)
  }
  expose(:comments) {
    content_plan.comments
                .roots
                .includes(:user, :commentable,  children: [:user, :parent, :commentable])
                .page(params[:page])
  }
  expose(:task) {
    Task.new(taskable: content_plan)
  }
  expose(:tasks) {
    content_plan.tasks.includes(:users).by_deadline
  }
  expose(:contents_search) {
    PlanContentsSearch.new(contents_search_params, sort_column, sort_direction)
  }
  expose(:contents) {
    contents_search.results.page(params[:page])
  }
  expose(:all_contents) {
    content_plan.contents
  }
  expose(:specialist_contents) {
    all_contents.specialist
  }
  expose(:mainstream_contents) {
    all_contents.mainstream
  }
  expose(:content_records_statuses) {
    contents.pluck(:status).uniq
  }
  expose(:all_records_are_live?) {
    content_records_statuses.size == 1 &&
    content_records_statuses[0] == "Live"
  }

  before_filter :authorize_user

  def index
    @search = ContentPlanSearch.new(params[:search])
    respond_to do |format|
      format.html
      format.json {
        render json: content_plans.map { |cp| { id: cp.id, text: cp.name } }
      }
    end
  end

  def show
    self.content_plan = ContentPlan.includes(:contents, :tasks)
                                   .find(params[:id])
  end

  def create
    if content_plan.save
      redirect_to content_plans_path, notice: "Content plan was successfully created."
    else
      render :new
    end
  end

  def versions
  end

  def update
    if content_plan.save
      redirect_to content_plan_path content_plan
    else
      render :edit
    end
  end

  def destroy
    content_plan.destroy
    redirect_to content_plans_path
  end

  def xls_export
    xls_data, xls_filename = ContentPlans::XlsExport.new(content_plan).run

    send_data(
      xls_data,
      filename: xls_filename,
      type: "application/vnd.ms-excel"
    )
  end

  private

  def content_plan_params
    params.require(:content_plan).permit(:tag_list,
                                         :status,
                                         :ref_no,
                                         :title,
                                         :details,
                                         :slug,
                                         :handover_detailed_guidance,
                                         :notes,
                                         :due_quarter,
                                         :due_year,
                                         user_ids: [],
                                         need_ids: [],
                                         organisation_ids: []
    )
  end

  def contents_search_params
    { content_plan_id: content_plan.id }
  end

  def authorize_user
    authorize content_plan
  end

  def require_all_records_to_be_live!
    unless all_records_are_live?
      redirect_to content_plan,
                  alert: "Excel export available only if all records have been changed to the 'live' status"
    end
  end

  def sort_column
    Content.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def content_plan_filter
    params[:id] || nil
  end
end

app/helpers/content_plans_helper.rb
module ContentPlansHelper
  def content_plan_tag_filters(tags)
    tags.map do |t|
      link_to(t, content_plans_path(search: { tag: t }), class: "tag")
    end.join.html_safe
  end

  def due_date_options_for_select
    ContentPlan::YEARS.map do |year|
      ContentPlan::QUARTERS.map do |quarter|
        "q#{quarter} #{year}"
      end
    end.flatten
  end

  def sortable_column(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to(title, content_plan_path(content_plan_filter, {sort: column, direction: direction}), class: css_class)
  end
end

app/views/content_plans/_contents_block.html.slim
.span8
  h4
    | Content Records
    = link_to "Add content",
              new_content_path(content_plan_id: content_plan.id),
              class: "btn btn-mini contents-btn"
  = render 'contents/search_form'
  .clearfix
  .contents_container
    = render 'contents/list'

app/views/content_plans/_form.html.slim
.form-margin.well
  = simple_form_for content_plan,
                    html: { class: 'form-horizontal form-container' } do |f|
    = f.input :ref_no
    .field_with_counter
      = f.input :title, input_html: { class: 'span12 string_with_counter' }
      .controls
        .countdown
    = f.input :details, input_html: {class: 'span12', rows: 10}
    = f.input :notes, input_html: {class: 'span12', rows: 10}
    = f.input :tag_list,
              as: :string,
              input_html: {class: "js-tags"}
    = f.association :users,
                    collection: User.all,
                    label: 'Users',
                    input_html: { style: "width:300px" }
    = f.input :need_ids,
              as: :select,
              collection: needs_options_for_select,
              input_html: {class: "js-needs", multiple: true}
    = f.input :organisation_ids,
              label: "Organisations",
              as: :select,
              collection: organisations_options_for_select,
              input_html: {class: "js-organisations", style: "width:300px", multiple: true}
    legend Due
    = f.input :due_quarter, label: "Quarter", as: :select, collection: ContentPlan::QUARTERS, include_blank: false
    = f.input :due_year, label: "Year", as: :select, collection: ContentPlan::YEARS, include_blank: false
    .control-group
      .controls
        = f.button :submit, class: 'btn-success'

app/views/content_plans/_status.html.slim
- cache([platform, content_plan, params[:q], params[:year], params[:organisation]], expires_in: 1.hour) do
  - if send("#{platform.downcase}_contents").any?
    .platform
      = platform
      .progress
        - Content.percentages_for(platform: platform, contents: send("#{platform.downcase}_contents")).each do |status, results|
            div[class="status status-#{status.parameterize}" style="width: #{results[1]}%" title="#{status}: #{results[1]}% (#{results[0]} items)" data-tooltip=true data-placement="bottom"]

app/views/content_plans/_version.html.slim
tr
  td.date
    = version.created_at.to_formatted_s(:long)
  td
    = version.user_name
  td
    = version.event
  td.changeset
    - version.changeset.each do |key, value|
      section[id="#{key}#{rand(10000)}" class="diff"]
        = key
        p.previous-version
          = value[0]
        p.current-version
          = value[1]

app/views/content_plans/edit.html.slim
= breadcrumb ["Content Plans", content_plans_path], [content_plan.name, content_plan_path(content_plan)], "Edit"

.container-fluid
  .row-fluid
    .span12
      h2
        Edit Content Plan
        - if policy(content_plan).destroy?
          = button_to "Delete", content_plan, method: :delete, class: 'btn btn-danger', form_class: 'delete-btn pull-right'

      = render "form"

app/views/content_plans/index.html.slim
- if policy(ContentPlan).new?
  = link_to "Add a Content Plan", new_content_plan_path, class: 'btn pull-right'

= breadcrumb "Content Plans"

.row
  .span12

    = form_for(search, url: content_plans_path, method: :get, as: :search, html: { class: 'form-inline search-form' }) do |f|
      = f.text_field :ref_no, placeholder: "Ref No.", class: "input-small"
      = f.select :organisation_ids,
                 options_for_select( organisations_options_for_select, search.organisation_ids ),
                 { include_blank: true },
                 { class: "js-organisations", style: "width:140px" }
      = f.select :need_id,
                 options_for_select( needs_options_for_select, search.need_id ),
                 { include_blank: true },
                 { class: "js-needs", style: "width:230px"}
      = f.select :user_id,
                 options_for_select( users_options_for_select, search.user_id ),
                 { include_blank: true },
                 { class: "js-users", style: "width:150px"}
      = f.text_field :tag, placeholder: "Tag", class: "js-tags", style: "width:220px"
      = f.select :due_date,
                 options_for_select(due_date_options_for_select, search.due_date),
                 { include_blank: true },
                 { class: "select2", placeholder: "Due Date", style: "width:100px" }
      = f.submit "Search", class: 'btn'

    = paginate content_plans

    table.table
      th Size
      th Organisations
      th Name
      th User Needs
      th Tags
      th Due
      - content_plans.each do |content_plan|
        - cache(content_plan) do
          tr
            td
              = content_plan.size
            td
              = content_organisations content_plan.organisations
            td
              = link_to content_plan.name, content_plan
            td
              = content_plan.decorate.needs_list
            td
              = content_plan_tag_filters content_plan.decorate.tags_list
            td
              = content_plan.due_date

app/views/content_plans/new.html.slim
= breadcrumb ["Content Plans", content_plans_path], "New"

.container-fluid
  .row-fluid
    .span12
      h2 New Content Plan
      = render "form"

app/views/content_plans/show.html.slim
- if policy(content_plan).edit?
  = link_to "edit", [:edit, content_plan], class: 'btn pull-right'
= link_to "history", [:versions, content_plan], class: 'btn pull-right history-btn'
= link_to "Excel export", xls_export_content_plan_path(content_plan.id), class: 'btn pull-right'

= breadcrumb ["Content Plans", content_plans_path], content_plan.name
.row
  .span12
    ul class="organisations-icon-list organisation"
      - content_plan.organisations.each do |organisation|
        li class=(organisation.organisation_brand_colour_class_name.to_s + "-brand-colour")
          a class=(logo_classes(class_name: organisation.organisation_logo_type_class_name, organisation: organisation, size: 'medium'))
            span
              = organisation_logo_name(organisation, content_plan.organisations.count == 1)
.row
  .span8
    h2
      = content_plan.name
    dl.metadata
      - if content_plan.size.present?
        dt Size:
        dd
          = content_plan.size
      - if content_plan.needs.present?
        dt User Needs:
        dd
          = content_plan.decorate.needs_list
      - if content_plan.users.any?
        dt Users:
        dd
          = content_plan.decorate.users_list
      - if content_plan.tag_list.present?
        dt Tags:
        dd
          = content_plan_tag_filters content_plan.decorate.tags_list
      - if content_plan.due_date.present?
        dt Due:
        dd
          = content_plan.due_date
      - if content_plan.organisations.any?
        dt Organisations:
        dd
          = content_plan.organisations.map(&:title).join("<br />").html_safe
  .span4.content-plans
    .tag-box.mini
      h4 Status
      = render 'content_plans/status', platform: 'Mainstream'
      = render 'content_plans/status', platform: 'Specialist'

.row
  .span12
    .content-plan-details
      .inner
        = govspeak content_plan.details

        - if content_plan.notes.present?
          h4 Notes
          = govspeak content_plan.notes
.row
  = render 'content_plans/contents_block'

  .span4.tasks-comments
    .inner
      h4 Tasks
      = render "tasks/form"

      = render "tasks/all"

      h4 Comments
      = render "comments/form"

      ul.comments
        = render 'comments/comments_list', commentable: content_plan.object

app/views/content_plans/versions.html.slim
h1
  =link_to "#{content_plan.title} history", content_plan
table.table
  thead
    tr
      th.time Time
      th.user User
      th.action Action
      th.changes Changes
  tbody
    = render partial: 'version', collection: content_plan.display_versions, as: :version