config/routes.rb
ContentPlanner::Application.routes.draw do
  resources :contents

  root to: "home#index"

  resources :content_plans do
    member do
      get 'versions'
      get :xls_export
    end
  end

  resources :tasks

  resources :comments do
    member do
      post :reply
    end
  end

  resources :users

  resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]

  get "dashboard_data", to: "home#dashboard_data"
  get "chart", to: "home#chart"

  get "/healthcheck" => proc { [200, {}, ["OK"]] }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, class_name: "Comment"

  has_many :children, class_name: "Comment",
                      foreign_key: :parent_id

  validates :commentable_id, presence: true
  validates :commentable_type, presence: true

  after_create :notify_users, if: "root?"

  scope :roots, -> { where parent_id: nil }

  paginates_per 7

  # Caching
  before_save :refresh_cache!
  before_destroy :refresh_cache!

  def notify_users
    CommentNotifier.new(self)
  end

  def root?
    !child?
  end

  def child?
    parent.present?
  end

  def reply_recipients
    children.map(&:user).uniq
  end

  private

  def refresh_cache!
    parent.touch if child?

    if root?
      children.each { |record| record.touch }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:comment, attributes: :comment_params)
  expose(:commentable) {
    params[:commentable_type].constantize.find(params[:commentable_id])
  }
  expose(:next_comments) {
    commentable.comments.roots.includes(:user, :commentable,  children: [:user, :parent, :commentable]).page(params[:page])
  }

  before_action :require_to_be_owner!, only: [:edit, :update, :destroy]
  before_action :check_ability_to_reply!, only: [:reply]

  def show
  end

  def create
    if comment.save(comment_params)
      redirect_to comment.commentable
    else
      render :new
    end
  end

  def edit
  end

  def update
    if comment.update(comment_params)
      redirect_to comment.commentable, notice: "Comment updated"
    else
      render :edit
    end
  end

  def destroy
    comment.destroy
    redirect_to comment.commentable, notice: "Comment deleted"
  end

  def reply
    reply_comment = Comments::Reply.new(comment,
                                        reply_params.merge(user: current_user)).run

    if reply_comment.success?
      redirect_to comment.commentable
    else
      redirect_to comment.commentable,
                  alert: reply_comment.errors
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :user_id, :commentable_id, :commentable_type)
  end

  def reply_params
    params.require(:reply).permit(:message)
  end

  def require_to_be_owner!
    comment_policy = CommentPolicy.new(current_user, comment)

    unless comment_policy.can_update_or_remove?
      notice = if !comment_policy.comment_author?
        "You have no permissions to #{action_name} this comment"
      elsif !comment_policy.comment_is_just_created?
        "Comment can be updated or deleted only in 5 minutes after posting"
      end

      redirect_to comment.commentable, notice: notice
    end
  end

  def check_ability_to_reply!
    self.comment = Comment.find(params[:id])

    unless CommentPolicy.new(current_user, comment).reply?
      redirect_to comment.commentable,
                  notice: "You can't reply on this comment"
    end
  end
end

app/views/comments/_action_links.html.slim
.comment_actions.pull-right
  - if policy(comment).reply?
    = link_to "Reply", "#",
              class: "btn btn-small reply_comment_link"

  - if policy(comment).can_update_or_remove?

    - if policy(comment).update?
      = link_to edit_comment_path(comment),
                class: "btn btn-small",
                data: { action: "edit_comment" } do
        i.icon-pencil

    - if policy(comment).destroy?
      = link_to comment_path(comment),
                method: :delete,
                class: "btn btn-small",
                data: { action: "delete_comment", confirm: "Are you sure?" } do
        i.icon-trash

app/views/comments/_comment.html.slim
- cache(comment) do
  li.comment id="#{dom_id(comment)}"
    .message
      = govspeak comment.message
    = render "comments/action_links", comment: comment
    span.name
      = link_to comment.user, comment.user
      |,
    span.created_at
      = comment.created_at.to_formatted_s(:long)
    - if policy(comment).reply?
      - if comment.children.present?
        ul.comment_children
          = render comment.children
      = render 'comments/reply_form', comment: comment

app/views/comments/_comments_list.html.slim
= render comments
= paginate comments, params: { controller: 'comments', action: 'index', commentable_type: commentable.class.name, commentable_id: commentable.id }, remote: true

app/views/comments/_form.html.slim
= simple_form_for comment,
                html: { class: 'form-container' } do |f|
  = f.input :message
  = f.input :commentable_id, as: :hidden
  = f.input :commentable_type, as: :hidden
  = f.input :user_id, as: :hidden

  .control-group
    .controls
      = f.button :submit, class: 'btn-success'

app/views/comments/_reply_form.html.slim
.reply_comment_form.hidden
  = simple_form_for :reply, url: reply_comment_path(comment),
                            as: :comment,
                            html: { class: 'form-container' } do |f|
    = f.input :message, as: :text, label: false
    = f.button :submit, 'Reply', class: 'btn btn-small btn-success pull-right'

app/views/comments/edit.html.slim
= breadcrumb [comment.commentable.to_s, comment.commentable], "Edit Comment"

.container-fluid
  .row-fluid
    .span12
      h2 Edit Comment
      .form-margin.well.edit_comment_form
        = render 'form'

app/views/comments/index.js.erb
$(".comments").html("<%= j(render('comments/comments_list', comments: next_comments, commentable: commentable)) %>");

app/views/comments/show.html.slim
= breadcrumb [comment.commentable.to_s, comment.commentable], "Comment Replies"

.container-fluid
  .row-fluid
    .span12
      h2 Comment Replies
  .row.comment_replies
    .span6
      ul.comments
        = render comment, from_comment_feed: true