config/routes.rb
ContentPlanner::Application.routes.draw do
  resources :contents

  root to: "home#index"

  resources :content_plans do
    member do
      get 'versions'
      get :xls_export
    end
  end

  resources :tasks

  resources :comments do
    member do
      post :reply
    end
  end

  resources :users

  resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]

  get "dashboard_data", to: "home#dashboard_data"
  get "chart", to: "home#chart"

  get "/healthcheck" => proc { [200, {}, ["OK"]] }

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authorize_user

  def index
    page = params[:page] || 1
    if params[:q].present?
      @tags = ActsAsTaggableOn::Tag.named_like(params[:q]).page(page).per(25)
    else
      @tags = ActsAsTaggableOn::Tag.page(page).per(25)
    end

    respond_to do |format|
      format.html {}
      format.json {
        render json: @tags.map { |t| { id: t.name, text: t.name } }
      }
    end
  end

  def new
    @tag = ActsAsTaggableOn::Tag.new
  end

  def create
    name = params[:tag][:name]
    if name.present?
      downcase_name = name.strip.mb_chars.downcase.to_s
      ActsAsTaggableOn::Tag.find_or_create_with_like_by_name(downcase_name)
    end
    redirect_to tags_path
  end

  def edit
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
  end

  def update
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    name = params[:tag][:name]
    downcase_name = name.strip.mb_chars.downcase.to_s
    @tag.name = downcase_name
    @tag.save!
    redirect_to tags_path
  end

  def destroy
    ActsAsTaggableOn::Tag.destroy(params[:id])
    redirect_to tags_path
  end

  def authorize_user
    authorize self
  end
end

app/views/tags/_form.html.slim
.form-margin.well
  = simple_form_for @tag, url: @tag.new_record? ? tags_path : tag_path,
                          as: :tag,
                          html: { class: 'form-horizontal form-container' } do |f|
    = f.input :name, input_html: { class: 'span4' }
    .control-group
      .controls
        = f.button :submit, @tag.new_record? ? 'Create Tag' : 'Edit Tag', class: 'btn-success'

app/views/tags/edit.html.slim
= breadcrumb ["Tags", tags_path], "Edit"

.container-fluid
  .row-fluid
    .span12
      h2 Edit Tag
      = render 'form'

app/views/tags/index.html.slim
= link_to "Add a Tag", new_tag_path, class: 'btn pull-right'
= breadcrumb "Tags"

.row
  .span12

    = paginate @tags

    table.table
      th Tag
      th &nbsp;
      th &nbsp;
      - @tags.each do |tag|
        tr
          td
            = tag.name
          td
            = link_to "edit", edit_tag_path(tag), class: "btn btn-default pull-right"
          td
            = button_to "delete", {action: :destroy, controller: :tags, id: tag.id}, method: :delete, class: "btn btn-danger pull-right"

app/views/tags/new.html.slim
= breadcrumb ["Tags", tags_path], "New"

.container-fluid
  .row-fluid
    .span12
      h2 New Tag
      = render 'form'