config/routes.rb
ContentPlanner::Application.routes.draw do
  resources :contents

  root to: "home#index"

  resources :content_plans do
    member do
      get 'versions'
      get :xls_export
    end
  end

  resources :tasks

  resources :comments do
    member do
      post :reply
    end
  end

  resources :users

  resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]

  get "dashboard_data", to: "home#dashboard_data"
  get "chart", to: "home#chart"

  get "/healthcheck" => proc { [200, {}, ["OK"]] }

end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
= link_to "GOV.UK Content Planner", root_path, :class => 'navbar-brand'
ul.nav
  - if user_signed_in?
    li
      = link_to "Maslow", Plek.current.find('maslow'), target: "_blank"
    = nav_item "Content Plans", content_plans_path, "content_plans"
    = nav_item "Content Records", contents_path, "contents"
    = nav_item "Tags", tags_path, "tags"
    li
      = link_to "Transition", Plek.current.find('transition'), target: "_blank"

p class='nav navbar-text pull-right'
  = current_user.name
  | &nbsp;|&nbsp;
  = link_to "Sign out", gds_sign_out_path

app/views/layouts/application.html.slim
doctype html
/[if lt IE 7]
  <html class="ie ie6 lte9 lte8 lte7">
/[if IE 7]
  <html class="ie ie7 lte9 lte8 lte7">
/[if IE 8]
  <html class="ie ie8 lte9 lte8">
/[if IE 9]
  <html class="ie ie9 lte9">
  | <!--[if (gte IE 9)|!(IE)]<!-->
html
  | <!--<![endif]-->
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport"
      title= content_for?(:title) ? yield(:title) : "Content Planner"
      meta content=(content_for?(:description) ? yield(:description) : "Content Planner") name="description"
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "modernizr"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  body class=("#{controller_name} #{action_name}")
    .navbar.navbar-fixed-top.navbar-inverse
      nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main role="main"
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          footer
      /! ! end of .container
    /! ! end of #main